# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies & lint
        run: |
          pip install flake8
          flake8 ./backend --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Install frontend dependencies & lint
        run: |
          npm install --prefix ./frontend
          npm run lint --prefix ./frontend

  test-backend:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    
    # --- ADD THIS BLOCK TO USE GITHUB SECRETS ---
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      # We can add dummy Supabase keys as the tests don't rely on them yet
      SUPABASE_URL: "http://dummy.url"
      SUPABASE_KEY: "dummy.key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install -r ./backend/requirements.txt

      - name: Run backend tests
        run: pytest ./backend/tests
