# .github/workflows/ci.yml
name: CI Pipeline

# This workflow runs on pushes and pull requests to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job will lint (check the style of) your code
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Match your Python version

      - name: Install backend dependencies & lint
        run: |
          pip install flake8
          # Run flake8, ignoring some common non-critical errors
          flake8 ./backend --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Install frontend dependencies & lint
        run: |
          npm install --prefix ./frontend
          npm run lint --prefix ./frontend

  # This job will run your backend tests
  test-backend:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    needs: lint # This job will only run if the 'lint' job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install -r ./backend/requirements.txt

      - name: Run backend tests
        run: pytest ./backend/tests
